---
- hosts: all
  become: true
  tasks:
    - name: install window manager
      pacman:
        name: 
          - i3-wm
          - polybar
          - network-manager-applet
          - dmenu
          - picom
          - feh
          - polkit
          - lib32-polkit
          - polkit-qt5 

